### ISSUE TITLE
wont compile on osx

### ISSUE THREAD

**Issue by kumavis** [ethereum/ethereumjs-tx#2]
```
─{🐓 } kumavis in ~/Development/Node/vapor-front on (master✱) 
╰─± npm install --save ethereumjs-tx
\
> secp256k1@0.0.16 install /Users/kumavis/Development/Node/vapor-front/node_modules/ethereumjs-tx/node_modules/secp256k1
> node-gyp rebuild

  CXX(target) Release/obj.target/secp256k1/secp256k1.o
../secp256k1.cc:479:68: warning: variable 'privKey' is uninitialized when used here [-Wuninitialized]
  int results = secp256k1_ec_privkey_export(secp256k1ctx, sk_data, privKey, &pk_len, compressed);
                                                                   ^~~~~~~
../secp256k1.cc:477:25: note: initialize the variable 'privKey' to silence this warning
  unsigned char *privKey;
                        ^
                         = NULL
1 warning generated.
  CC(target) Release/obj.target/secp256k1/secp256k1-src/src/secp256k1.o
In file included from ../secp256k1-src/src/secp256k1.c:14:
In file included from ../secp256k1-src/src/scalar_impl.h:20:
../secp256k1-src/src/scalar_4x64_impl.h:70:5: error: use of undeclared identifier 'uint128_t'
    uint128_t t;
    ^
../secp256k1-src/src/scalar_4x64_impl.h:72:5: error: use of undeclared identifier 't'
    t = (uint128_t)r->d[0] + overflow * SECP256K1_N_C_0;
    ^
../secp256k1-src/src/scalar_4x64_impl.h:72:10: error: use of undeclared identifier 'uint128_t'
    t = (uint128_t)r->d[0] + overflow * SECP256K1_N_C_0;
         ^
../secp256k1-src/src/scalar_4x64_impl.h:73:15: error: use of undeclared identifier 't'
    r->d[0] = t & 0xFFFFFFFFFFFFFFFFULL; t >>= 64;
              ^
../secp256k1-src/src/scalar_4x64_impl.h:73:42: error: use of undeclared identifier 't'
    r->d[0] = t & 0xFFFFFFFFFFFFFFFFULL; t >>= 64;
                                         ^
../secp256k1-src/src/scalar_4x64_impl.h:74:5: error: use of undeclared identifier 't'
    t += (uint128_t)r->d[1] + overflow * SECP256K1_N_C_1;
    ^
../secp256k1-src/src/scalar_4x64_impl.h:74:11: error: use of undeclared identifier 'uint128_t'
    t += (uint128_t)r->d[1] + overflow * SECP256K1_N_C_1;
          ^
../secp256k1-src/src/scalar_4x64_impl.h:75:15: error: use of undeclared identifier 't'
    r->d[1] = t & 0xFFFFFFFFFFFFFFFFULL; t >>= 64;
              ^
../secp256k1-src/src/scalar_4x64_impl.h:75:42: error: use of undeclared identifier 't'
    r->d[1] = t & 0xFFFFFFFFFFFFFFFFULL; t >>= 64;
                                         ^
../secp256k1-src/src/scalar_4x64_impl.h:76:5: error: use of undeclared identifier 't'
    t += (uint128_t)r->d[2] + overflow * SECP256K1_N_C_2;
    ^
../secp256k1-src/src/scalar_4x64_impl.h:76:11: error: use of undeclared identifier 'uint128_t'
    t += (uint128_t)r->d[2] + overflow * SECP256K1_N_C_2;
          ^
../secp256k1-src/src/scalar_4x64_impl.h:77:15: error: use of undeclared identifier 't'
    r->d[2] = t & 0xFFFFFFFFFFFFFFFFULL; t >>= 64;
              ^
../secp256k1-src/src/scalar_4x64_impl.h:77:42: error: use of undeclared identifier 't'
    r->d[2] = t & 0xFFFFFFFFFFFFFFFFULL; t >>= 64;
                                         ^
../secp256k1-src/src/scalar_4x64_impl.h:78:5: error: use of undeclared identifier 't'
    t += (uint64_t)r->d[3];
    ^
../secp256k1-src/src/scalar_4x64_impl.h:79:15: error: use of undeclared identifier 't'
    r->d[3] = t & 0xFFFFFFFFFFFFFFFFULL;
              ^
../secp256k1-src/src/scalar_4x64_impl.h:85:5: error: use of undeclared identifier 'uint128_t'
    uint128_t t = (uint128_t)a->d[0] + b->d[0];
    ^
../secp256k1-src/src/scalar_4x64_impl.h:86:15: error: use of undeclared identifier 't'
    r->d[0] = t & 0xFFFFFFFFFFFFFFFFULL; t >>= 64;
              ^
../secp256k1-src/src/scalar_4x64_impl.h:86:42: error: use of undeclared identifier 't'
    r->d[0] = t & 0xFFFFFFFFFFFFFFFFULL; t >>= 64;
                                         ^
../secp256k1-src/src/scalar_4x64_impl.h:87:5: error: use of undeclared identifier 't'
    t += (uint128_t)a->d[1] + b->d[1];
    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/secp256k1/secp256k1-src/src/secp256k1.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/kumavis/Development/Node/vapor-front/node_modules/ethereumjs-tx/node_modules/secp256k1
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 

> sha3@1.1.0 install /Users/kumavis/Development/Node/vapor-front/node_modules/ethereumjs-tx/node_modules/ethereumjs-util/node_modules/sha3
> node-gyp rebuild

  CXX(target) Release/obj.target/sha3/src/addon.o
  CXX(target) Release/obj.target/sha3/src/displayIntermediateValues.o
  CXX(target) Release/obj.target/sha3/src/KeccakF-1600-reference.o
  CXX(target) Release/obj.target/sha3/src/KeccakNISTInterface.o
  CXX(target) Release/obj.target/sha3/src/KeccakSponge.o
  SOLINK_MODULE(target) Release/sha3.node
  SOLINK_MODULE(target) Release/sha3.node: Finished
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/share/npm/bin/npm" "install" "--save" "ethereumjs-tx"
npm ERR! node v0.12.0
npm ERR! npm  v2.9.1
npm ERR! code ELIFECYCLE

npm ERR! secp256k1@0.0.16 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the secp256k1@0.0.16 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kumavis/Development/Node/vapor-front/npm-debug.log
```

**Comment by wanderer** [comment]
moved to secp256k1 repo

**Comment by wanderer** [comment]
https://github.com/wanderer/secp256k1-node/issues/25
