### ISSUE TITLE
Error when installed using NPM

### ISSUE THREAD

**Issue by KenKappler** [ethereum/ethereumjs-tx#6]
This may also be linked t this issue raised on the embark framework: https://github.com/iurimatias/embark-framework/issues/99

```
Kens-MacBook-Air:~ KenKappler$ npm install ethereumjs-tx
 
> secp256k1@1.1.4 install /Users/KenKappler/node_modules/ethereumjs-tx/node_modules/secp256k1
> node-gyp rebuild

  CXX(target) Release/obj.target/secp256k1/functions.o
../functions.cc:224:57: warning: variable 'pub_key' is uninitialized when used here [-Wuninitialized]
  int results = secp256k1_ec_pubkey_parse(secp256k1ctx, pub_key, pk_data, pub_len);
                                                        ^~~~~~~
../functions.cc:223:30: note: initialize the variable 'pub_key' to silence this warning
  secp256k1_pubkey_t *pub_key;
                             ^
                              = nullptr
../functions.cc:248:56: warning: variable 'pub_key' is uninitialized when used here [-Wuninitialized]
  int results= secp256k1_ec_pubkey_parse(secp256k1ctx, pub_key, pk_data, pub_len);
                                                       ^~~~~~~
../functions.cc:247:30: note: initialize the variable 'pub_key' to silence this warning
  secp256k1_pubkey_t *pub_key;
                             ^
                              = nullptr
2 warnings generated.
  CXX(target) Release/obj.target/secp256k1/util.o
  CXX(target) Release/obj.target/secp256k1/secp256k1.o
  CC(target) Release/obj.target/secp256k1/secp256k1-src/src/secp256k1.o
In file included from ../secp256k1-src/src/secp256k1.c:12:
In file included from ../secp256k1-src/src/num_impl.h:14:
In file included from ../secp256k1-src/src/num.h:17:
../secp256k1-src/src/num_gmp.h:10:10: fatal error: 'gmp.h' file not found
#include <gmp.h>
         ^
1 error generated.
make: *** [Release/obj.target/secp256k1/secp256k1-src/src/secp256k1.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/KenKappler/node_modules/ethereumjs-tx/node_modules/secp256k1
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 

> sha3@1.2.0 install /Users/KenKappler/node_modules/ethereumjs-tx/node_modules/ethereumjs-util/node_modules/sha3
> node-gyp rebuild

  CXX(target) Release/obj.target/sha3/src/addon.o
  CXX(target) Release/obj.target/sha3/src/displayIntermediateValues.o
  CXX(target) Release/obj.target/sha3/src/KeccakF-1600-reference.o
  CXX(target) Release/obj.target/sha3/src/KeccakNISTInterface.o
  CXX(target) Release/obj.target/sha3/src/KeccakSponge.o
  SOLINK_MODULE(target) Release/sha3.node
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "ethereumjs-tx"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! secp256k1@1.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the secp256k1@1.1.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/KenKappler/npm-debug.log
```
npm debug log:
https://gist.github.com/KenKappler/3711fd9c9068f85f00f3

**Comment by wanderer** [comment]
thanks @KenKappler what OS are you running?

**Comment by KenKappler** [comment]
MAC OSX el capitan

**Comment by kumavis** [comment]
guess I wont be upgrading soon...

**Comment by tcoulter** [comment]
@kumavis you lucky dog. I already did...

**Comment by KenKappler** [comment]
I'm actually getting the same issue on yosemite as well....

**Comment by wanderer** [comment]
ok guys this is got a be related to GMP depency not being installed.  secp256k1 has a script to test if gmp is installed or not. I'm guessing it giving a false positive. I would love some help testing this on mac. Could you download https://github.com/wanderer/secp256k1-node/blob/master/utils/has_lib.sh  and run `./has_lib.sh gmpxx`?

**Comment by tcoulter** [comment]
@wanderer 

```
Tims-MacBook-Pro:Consensys tim$ ./has_lib.sh 
true
```

**Comment by wanderer** [comment]
@tcoulter what does  ./has_lib.sh  some_random_button_mashing do?

**Comment by tcoulter** [comment]
@wanderer 

```
Tims-MacBook-Pro:Consensys tim$ ./has_lib.sh asdfasdf
false
```

**Comment by tcoulter** [comment]
Whoops, looks like I ran the wrong thing:

@wanderer 

```
Tims-MacBook-Pro:Consensys tim$ ./has_lib.sh gmpxx
true
```

**Comment by wanderer** [comment]
@KenKappler can you please try install the latest version of secp256k1? 
`git clone git@github.com:wanderer/secp256k1-node.git`
`cd secp256k1-node`
`npm install`

Let me know what happens! thanks.

**Comment by taoeffect** [comment]
See related discussion in https://github.com/wanderer/secp256k1-node/issues/35

**Comment by taoeffect** [comment]
This should be fixed as soon as @wanderer merges https://github.com/wanderer/secp256k1-node/pull/36 and publishes new version to NPM.

**Comment by wanderer** [comment]
@taoeffect @KenKappler alright just push ethereumjs-tx 0.6.8 with the updated secp256k1

**Comment by stanacton** [comment]
FYI - I had the same issue after I installed MAC OSX el capitan and I was able to fix it by running the following command:

  xcode-select --install

**Comment by yogiben** [comment]
@stanacton thanks for alleviating my insanity

**Comment by jesusdiazvico** [comment]
FWIW, I sitll had the same issue on Ubuntu 14.04.4 (node v.5.4.1 and 3.3.12). Got it working installing secp256k1-node separately as suggested by @wanderer on his message of 21 Oct 2015.

**Comment by theotow** [comment]
@stanacton thanks
